import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {parseCSV,rebase,analyze,decimalAdd,decimalSubtract} from '../src/core.mjs';import {exportFiles} from '../src/export.mjs';
const input={oldCSV:fs.readFileSync(new URL('../fixtures/old.csv',import.meta.url),'utf8'),newCSV:fs.readFileSync(new URL('../fixtures/new.csv',import.meta.url),'utf8'),oldCRS:'EPSG:3857',newCRS:'EPSG:3857'},choices={A:'follow',B:'keep',D:'follow'};
test('stable exact string keys, changed provider row order, pinned/automatic and removal',()=>{const r=rebase(input,choices),by=Object.fromEntries(r.rows.map(x=>[x.stable_key,x]));assert.equal(by.A.label_x,'22');assert.equal(by.A.label_y,'28');assert.equal(by.B.label_x,'112');assert.equal(by.B.label_y,'8');assert.equal(by.D.label_show,'0');assert.equal(by.D.label_x,'342');assert.equal(by.C.label_state,'auto');assert.equal(by.N.label_state,'auto');assert.equal(by['007'].label_x,'512');assert.equal(by['7'].label_x,'612');assert.deepEqual(r.removed,['E']);});
test('moved pinned requires deliberate decisions',()=>assert.throws(()=>rebase(input),e=>e.code==='DECISION_REQUIRED'));
test('reset makes automatic and preserves hidden visibility',()=>{const r=rebase(input,{A:'reset',B:'reset',D:'reset'});for(const key of ['A','B','D']){const row=r.rows.find(x=>x.stable_key===key);assert.equal(row.label_state,'auto');assert.equal(row.label_x,'');assert.equal(row.label_rotation,'0');}assert.equal(r.rows.find(x=>x.stable_key==='D').label_show,'0');});
test('exact decimal displacement',()=>{assert.equal(decimalAdd('0.1','0.2'),'0.3');assert.equal(decimalSubtract('3e-2','0.01'),'0.02');assert.equal(decimalAdd('-0','0'),'0');});
test('strict CSV preserves comma and quotes',()=>assert.deepEqual(parseCSV('a,b\r\n"007","say ""Hi"", please"\r\n').rows,[['007','say "Hi", please']]));
test('malformed CSV and dangerous numbers block',()=>{for(const text of ['a,a\n1,2','a,b\n1','a,b\n"1,2','a,b\n"1"z,2'])assert.throws(()=>parseCSV(text));for(const value of ['NaN','Infinity','-Infinity','0x12','1e40'])assert.throws(()=>rebase({...input,newCSV:input.newCSV.replace('B,120','B,'+value)},choices));});
test('CRS mismatch, geographic CRS, duplicate keys and partial anchors block',()=>{assert.throws(()=>rebase({...input,newCRS:'EPSG:3395'},choices),e=>e.code==='CRS_MISMATCH');assert.throws(()=>rebase({...input,newCRS:'EPSG:4326'},choices),e=>e.code==='CRS_UNSUPPORTED');assert.throws(()=>rebase({...input,newCSV:input.newCSV+'A,1,2,Duplicate\n'},choices),e=>e.code==='DUPLICATE_KEY');assert.throws(()=>rebase({...input,oldCSV:input.oldCSV.replace('A,0,0,12,8','A,0,0,,8')},choices),e=>e.code==='LABEL_PAIR');});
test('special object keys are exact identities',()=>{const i={...input,oldCSV:'key,x,y,label_x,label_y,rotation,show\n__proto__,0,0,1,2,0,1\nconstructor,5,6,7,8,0,1',newCSV:'key,x,y,text\nconstructor,5,6,Hello\n__proto__,1,1,World'};const r=rebase(i,JSON.parse('{"__proto__":"follow"}'));assert.equal(r.rows[1].label_x,'2');});
test('extra and stale decisions blocked',()=>assert.throws(()=>rebase(input,{...choices,N:'follow'}),e=>e.code==='INVALID_DECISION'));
test('receipt source hashes and portable field binding outputs',async()=>{const f=await exportFiles(input,choices),d=JSON.parse(f['decisions.json']);assert.match(d.sourceHashes.old,/^[a-f0-9]{64}$/);assert.match(f['rebased.qgs'],/file:\.\/rebased.csv/);assert.match(f['rebased.qml'],/name="PositionX"/);assert.match(f['rebased.csvt'],/^"String","Real"/);assert.equal(JSON.parse(f['labelrebase-project.json']).input.oldCSV,input.oldCSV);});

test('QGIS CRS native XML includes real legacy IDs and enabled project projection',async()=>{for(const [crs,id] of [['EPSG:3857',3857],['EPSG:3395',1353],['EPSG:32601',3085],['EPSG:32660',3144],['EPSG:32701',3151],['EPSG:32760',3210]]){const f=await exportFiles({...input,oldCRS:crs,newCRS:crs},choices),q=f['rebased.qgs'];assert.equal((q.match(new RegExp('<srsid>'+id+'</srsid>','g'))||[]).length,3);assert.match(q,/<ProjectionsEnabled type="int">1<\/ProjectionsEnabled>/);assert.ok(q.includes('<ProjectCrs type="QString">'+crs+'</ProjectCrs>'));}});

test('small exponent arithmetic survives canonical expansion',()=>{assert.equal(decimalAdd('1e-30','1e-30'),'0.000000000000000000000000000002');assert.equal(decimalSubtract('1e-30','0'),'0.000000000000000000000000000001');});
test('unsupported controls and exact coordinate overflow block',()=>{assert.throws(()=>parseCSV('a,b\n1,\0'),e=>e.code==='CSV_CONTROL');assert.throws(()=>rebase({...input,newCSV:input.newCSV.replace('B,120','B,1000000000000.0000001')},choices),e=>e.code==='NUMBER_RANGE');});

test('normalize carry before precision validation and allow exact internal cancellation',()=>{assert.equal(decimalAdd('0.'+'9'.repeat(30),'1e-30'),'1');const i={oldCSV:'key,x,y,label_x,label_y,rotation,show\nA,1000000000000,0,1000000000000,0,0,1',newCSV:'key,x,y,text\nA,1e-30,0,Alpha',oldCRS:'EPSG:3857',newCRS:'EPSG:3857'};const a=analyze(i);assert.equal(a.changes.length,1);assert.equal(rebase(i,{A:'follow'}).rows[0].label_x,'0.'+'0'.repeat(29)+'1');assert.equal(rebase(i,{A:'keep'}).rows[0].label_x,'1000000000000');assert.equal(rebase(i,{A:'reset'}).rows[0].label_x,'');});
test('EPSG authority codes must be canonical exact strings',()=>assert.throws(()=>rebase({...input,oldCRS:'EPSG:03857',newCRS:'EPSG:03857'},choices),e=>e.code==='CRS_UNSUPPORTED'));

test('UTF-8 byte caps and column/name limits agree with file import',()=>{assert.throws(()=>parseCSV('日'.repeat(700000)),e=>e.code==='CSV_SIZE');assert.throws(()=>parseCSV(Array.from({length:257},(_,i)=>'c'+i).join(',')+'\n'+Array(257).fill('1').join(',')),e=>e.code==='COLUMN_LIMIT');assert.throws(()=>parseCSV('a'.repeat(257)+'\n1'),e=>e.code==='CSV_HEADER');});
test('rotation bounds use exact decimals',()=>{for(const sign of ['','-'])assert.throws(()=>rebase({...input,oldCSV:input.oldCSV.replace('A,0,0,12,8,0,1','A,0,0,12,8,'+sign+'360.'+'0'.repeat(26)+'1,1')},choices),e=>e.code==='ROTATION_RANGE');});
