import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url)),dist=path.join(root,'dist');await fs.mkdir(dist,{recursive:true});
const demo={oldCSV:await fs.readFile(path.join(root,'fixtures/old.csv'),'utf8'),newCSV:await fs.readFile(path.join(root,'fixtures/new.csv'),'utf8'),oldCRS:'EPSG:3857',newCRS:'EPSG:3857'};
await fs.writeFile(path.join(root,'src/demo.mjs'),'// Authored synthetic fixture; generated by scripts/build.mjs.\nexport const DEMO='+JSON.stringify(demo).replaceAll('<','\\u003c')+';\n');
for(const directory of ['src','web'])await fs.cp(path.join(root,directory),path.join(dist,directory),{recursive:true});
const template=await fs.readFile(path.join(root,'web/index.html'),'utf8'),style=await fs.readFile(path.join(root,'web/styles.css'),'utf8');
const modules=['src/core.mjs','src/zip.mjs','src/export.mjs','src/project.mjs','src/demo.mjs','web/i18n.mjs','web/app.mjs'];
let script='';for(const file of modules){const code=await fs.readFile(path.join(root,file),'utf8');script+='\n// '+file+'\n'+code.replace(/^import[^\n]+\n/gm,'').replace(/^export\s+/gm,'');}
if(script.includes('</script'))throw Error('Unexpected closing script sequence in own source');
const html=template.replace('<link rel="stylesheet" href="./styles.css">','<style>'+style+'</style>').replace('<script type="module" src="./app.mjs"></script>','<script type="module">'+script+'</script>');
await fs.writeFile(path.join(dist,'index.html'),html);console.log('Built original-source static app and standalone HTML; no runtime dependency or network.');
