import {rebase} from './core.mjs';
import {zipFiles} from './zip.mjs';
export const HEADERS=['stable_key','point_x','point_y','label_text','label_x','label_y','label_rotation','label_show','label_state'];
const csvCell=v=>/[",\r\n]/.test(String(v))?'"'+String(v).replaceAll('"','""')+'"':String(v);
export const xml=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;');
function properties(){return `<dd_properties><Option type="Map"><Option name="name" type="QString" value=""/><Option name="type" type="QString" value="collection"/><Option name="properties" type="Map">${Object.entries({PositionX:'label_x',PositionY:'label_y',LabelRotation:'label_rotation',Show:'label_show'}).map(([name,field])=>`<Option name="${name}" type="Map"><Option name="active" type="bool" value="true"/><Option name="field" type="QString" value="${field}"/><Option name="type" type="int" value="2"/></Option>`).join('')}</Option></Option></dd_properties>`;}
const labeling=()=>`<labeling type="simple"><settings><text-style fieldName="label_text" isExpression="0" fontFamily="DejaVu Sans" fontSize="10" fontWeight="50" fontItalic="0" fontLetterSpacing="0" fontWordSpacing="0" namedStyle="Regular" fontSizeUnit="Point" textColor="20,30,40,255"/><text-format/><placement placement="0" dist="0" distUnits="MM"/><rendering drawLabels="1" obstacle="0"/>${properties()}</settings></labeling>`;
const symbol=()=>`<renderer-v2 type="singleSymbol" symbollevels="0" enableorderby="0"><symbols><symbol type="marker" name="0" alpha="1"><layer class="SimpleMarker" enabled="1" pass="0"><Option type="Map"><Option name="name" type="QString" value="circle"/><Option name="color" type="QString" value="23,119,115,255"/><Option name="outline_color" type="QString" value="255,255,255,255"/><Option name="outline_width" type="QString" value="0.3"/><Option name="size" type="QString" value="2"/><Option name="size_unit" type="QString" value="MM"/></Option></layer></symbol></symbols></renderer-v2>`;
// QGIS's official legacy ID map; readXml requires a positive system srsid
// before consulting authid. These are actual native IDs, not EPSG guesses.
const spatialRef=crs=>{const code=Number(crs.split(':')[1]),id=code===3857?3857:code===3395?1353:code<32700?code-29516:code-29550;return `<spatialrefsys><srsid>${id}</srsid><srid>${code}</srid><authid>${xml(crs)}</authid></spatialrefsys>`;};
const srs=crs=>`<srs>${spatialRef(crs)}</srs>`;
export function nativeXML(result){const {crs,rows}=result,pts=rows.flatMap(r=>[[+r.point_x,+r.point_y],...(r.label_x!==''?[[+r.label_x,+r.label_y]]:[])]),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),pad=Math.max(20,(Math.max(...xs)-Math.min(...xs))*.1,(Math.max(...ys)-Math.min(...ys))*.1),extent=`<extent><xmin>${Math.min(...xs)-pad}</xmin><ymin>${Math.min(...ys)-pad}</ymin><xmax>${Math.max(...xs)+pad}</xmax><ymax>${Math.max(...ys)+pad}</ymax></extent>`;
 const style=symbol()+labeling();const uri=`file:./rebased.csv?type=csv&detectTypes=yes&xField=point_x&yField=point_y&crs=${crs}&spatialIndex=no&subsetIndex=no&watchFile=no`;
 return {'rebased.qml':`<?xml version="1.0" encoding="UTF-8"?>\n<qgis version="3.34.0" labelsEnabled="1" styleCategories="Symbology|Labeling">${style}</qgis>\n`,
 'rebased.qgs':`<?xml version="1.0" encoding="UTF-8"?>\n<qgis version="3.34.0" projectname="LabelRebase"><title>LabelRebase</title><projectCrs>${spatialRef(crs)}</projectCrs><mapcanvas><units>meters</units>${extent}<destinationsrs>${spatialRef(crs)}</destinationsrs></mapcanvas><layer-tree-group name="" checked="Qt::Checked"><layer-tree-layer id="labelrebase_points" name="Rebased labels" checked="Qt::Checked" source="${xml(uri)}" providerKey="delimitedtext"/></layer-tree-group><projectlayers><maplayer type="vector" geometry="Point" labelsEnabled="1" hasScaleBasedVisibilityFlag="0"><id>labelrebase_points</id><layername>Rebased labels</layername><datasource>${xml(uri)}</datasource><provider encoding="UTF-8">delimitedtext</provider>${srs(crs)}${extent}${style}</maplayer></projectlayers><properties><SpatialRefSys><ProjectionsEnabled type="int">1</ProjectionsEnabled><ProjectCrs type="QString">${xml(crs)}</ProjectCrs></SpatialRefSys><Paths><Absolute type="bool">false</Absolute></Paths></properties></qgis>\n`};}
async function sha(text){const bytes=new TextEncoder().encode(text),sum=await globalThis.crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(sum)].map(b=>b.toString(16).padStart(2,'0')).join('');}
export async function exportFiles(input,decisions={}){const r=rebase(input,decisions),receipt={format:'label-rebase-decisions',version:1,crs:r.crs,sourceHashes:{old:await sha(input.oldCSV),new:await sha(input.newCSV)},oldMapping:r.oldMapping,newMapping:r.newMapping,decisions:r.decisions,removedKeys:r.removed,newKeys:r.added,counts:{old:r.rows.length-r.added.length+r.removed.length,new:r.rows.length,removed:r.removed.length,added:r.added.length},rows:r.rows.map(v=>({key:v.stable_key,decision:v.decision,labelState:v.label_state,visible:v.label_show==='1'})),limits:['Point geometry, identical declared projected CRS','Single-line labels, authored minimal style','No reprojection or arbitrary source style preservation','Automatic labels may collide or be suppressed; review in QGIS']};
 return {'rebased.csv':HEADERS.join(',')+'\r\n'+r.rows.map(row=>HEADERS.map(h=>csvCell(row[h])).join(',')).join('\r\n')+'\r\n','rebased.csvt':'"String","Real","Real","String","Real","Real","Real","Integer","String"\n',...nativeXML(r),'decisions.json':JSON.stringify(receipt,null,2)+'\n','labelrebase-project.json':JSON.stringify({format:'label-rebase-project',version:1,input:{...input,oldMapping:r.oldMapping,newMapping:r.newMapping},decisions:r.decisions},null,2)+'\n','README.txt':'Open rebased.qgs in QGIS. Keep all files together when moving the folder.\nThe minimal authored style is also available as rebased.qml.\nlabelrebase-project.json contains both original input CSVs and the decisions; keep it private if the source data is private.\nCRS declarations are trusted, not inferred. No reprojection is performed.\nNever edit keys through spreadsheet numeric conversion: 007 and 7 are different.\nAutomatic labels are subject to QGIS placement and collision rules.\n'};}
export const exportZip=async(input,decisions)=>zipFiles(await exportFiles(input,decisions));
