import {analyze,rebase,parseCSV,DEFAULT_OLD,DEFAULT_NEW,decimalAdd} from '../src/core.mjs';
import {exportZip} from '../src/export.mjs';
import {parseProject} from '../src/project.mjs';
import {DEMO} from '../src/demo.mjs';
import {MESSAGES} from './i18n.mjs';
const $=id=>document.getElementById(id);
const escapeHTML=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
let locale='ja',revision=0,clearGeneration=0,projectVersion=0,busy=false,analysisState=null,readyResult=null,decisionPage=0;
let choices=Object.create(null),mappings={old:{...DEFAULT_OLD},new:{...DEFAULT_NEW}},fileVersions={old:0,new:0};
let statusState={key:'intro',params:{},kind:'neutral'};
const roles={old:['key','x','y','labelX','labelY','rotation','show'],new:['key','x','y','text']};
function tr(key,params={}){let value=MESSAGES[locale][key]??MESSAGES[locale].errorGeneric;for(const [name,v] of Object.entries(params))value=value.replaceAll('{'+name+'}',String(v));return value;}
function showStatus(key,params={},kind='neutral'){statusState={key,params,kind};$('status').textContent=tr(key,params);$('status').dataset.kind=kind;}
function showError(error){showStatus(MESSAGES[locale][error.code]?error.code:'fileError',{},'error');if(error.key)$('status').textContent+=' ['+error.key+']';}
function readInput(){return {oldCSV:$('oldCSV').value,newCSV:$('newCSV').value,oldCRS:$('oldCRS').value.trim(),newCRS:$('newCRS').value.trim(),oldMapping:{...mappings.old},newMapping:{...mappings.new}};}
function invalidate(key='changed'){revision++;busy=false;analysisState=null;readyResult=null;choices=Object.create(null);decisionPage=0;$('result').replaceChildren();$('result').hidden=true;setButtons();showStatus(key);}
function setButtons(){const blocked=!readyResult||busy;$('export').disabled=blocked;$('saveProject').disabled=blocked;}
function renderMappings(side,auto=false){let headers=[];try{headers=parseCSV($(side+'CSV').value).headers;}catch{}
 const defaults=side==='old'?DEFAULT_OLD:DEFAULT_NEW;
 const html=roles[side].map(role=>{const optional=role==='rotation'||role==='show';let selected=mappings[side][role];if(selected===undefined||(auto&&selected==='')||(selected!==''&&!headers.includes(selected)))selected=headers.includes(defaults[role])?defaults[role]:'';mappings[side][role]=selected;
 return `<label for="map-${side}-${role}">${escapeHTML(tr(role))}<select id="map-${side}-${role}" data-map-side="${side}" data-map-role="${role}"><option value="">${escapeHTML(tr(optional?'none':'pickColumn'))}</option>${headers.map(h=>`<option value="${escapeHTML(h)}"${selected===h?' selected':''}>${escapeHTML(h)}</option>`).join('')}</select></label>`;}).join('');
 $(side+'Mapping').innerHTML=html;
 for(const select of $(side+'Mapping').querySelectorAll('select'))select.addEventListener('change',()=>{mappings[side][select.dataset.mapRole]=select.value;projectVersion++;fileVersions[side]++;invalidate();});
}
function translate(){document.documentElement.lang=locale;for(const element of document.querySelectorAll('[data-i18n]'))element.innerHTML=tr(element.dataset.i18n);renderMappings('old');renderMappings('new');if(analysisState)renderResult();else showStatus(statusState.key,statusState.params,statusState.kind);}
function labelPosition(change){const o=change.old;if(!o||o.labelX==='')return null;const policy=change.requiresDecision?choices[change.key]:'unchanged';if(policy==='reset')return null;if(change.requiresDecision&&!policy)return null;try{return policy==='follow'?[decimalAdd(o.labelX,change.dx),decimalAdd(o.labelY,change.dy)]:[o.labelX,o.labelY];}catch{return undefined;}}
function previewSVG(){const changes=analysisState.changes.slice(0,200),points=[];for(const c of changes){points.push([+c.new.x,+c.new.y]);if(c.old){points.push([+c.old.x,+c.old.y]);if(c.old.labelX!=='')points.push([+c.old.labelX,+c.old.labelY]);}const p=labelPosition(c);if(p)points.push(p.map(Number));}
 const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),rangeX=Math.max(maxX-minX,1),rangeY=Math.max(maxY-minY,1),scale=Math.min(400/rangeX,195/rangeY),offsetX=42+(400-rangeX*scale)/2,offsetY=35+(195-rangeY*scale)/2;
 const px=x=>offsetX+(Number(x)-minX)*scale,py=y=>255-offsetY-(Number(y)-minY)*scale;
 let marks='';for(const c of changes){const x=px(c.new.x),y=py(c.new.y),p=labelPosition(c);if(c.old){const ox=px(c.old.x),oy=py(c.old.y);marks+=`<line x1="${ox}" y1="${oy}" x2="${x}" y2="${y}" stroke="#9aafa0" stroke-dasharray="3 3"/><circle cx="${ox}" cy="${oy}" r="4" fill="#fffefa" stroke="#84958a" stroke-width="1.5"/>`;if(c.old.labelX!=='')marks+=`<rect x="${px(c.old.labelX)-3}" y="${py(c.old.labelY)-3}" width="6" height="6" fill="none" stroke="#b1bcb0"/>`;}
 if(p){const lx=px(p[0]),ly=py(p[1]);marks+=`<line x1="${x}" y1="${y}" x2="${lx}" y2="${ly}" stroke="#c89b38" stroke-width="1.2"/><rect x="${lx-3.5}" y="${ly-3.5}" width="7" height="7" fill="#e5af49" stroke="#997329"${c.old?.show==='0'?' opacity=".45"':''}/>`;}
 marks+=`<circle cx="${x}" cy="${y}" r="4.5" fill="#176e64"/><text x="${x+6}" y="${y+16}" fill="#355748" font-size="10">${escapeHTML(c.key.length>14?c.key.slice(0,13)+'…':c.key)}</text>`;}
 return `<svg viewBox="0 0 490 280" role="img" aria-label="${escapeHTML(tr('preview'))}"><title>${escapeHTML(tr('preview'))}</title><path d="M30 240H470M30 30V240" fill="none" stroke="#d2ded0"/>${marks}</svg>`;
}
function renderResult(){if(!analysisState)return;const activeKey=document.activeElement?.dataset?.decisionKey;
 const required=analysisState.changes.filter(c=>c.requiresDecision),pending=required.filter(c=>!Object.hasOwn(choices,c.key));let resultError=null;
 try{readyResult=rebase(readInput(),choices);}catch(error){readyResult=null;if(error.code!=='DECISION_REQUIRED')resultError=error;}
 setButtons();
 const counts={moved:analysisState.changes.filter(c=>c.status==='moved').length,unchanged:analysisState.changes.filter(c=>c.status==='unchanged').length,new:analysisState.changes.filter(c=>c.status==='new').length,removed:analysisState.removed.length,need:pending.length};
 const pageCount=Math.max(1,Math.ceil(required.length/25));decisionPage=Math.min(decisionPage,pageCount-1);
 const cards=required.slice(decisionPage*25,decisionPage*25+25).map((c,index)=>{const pos=labelPosition(c),selected=choices[c.key]||'',id='decision-'+(decisionPage*25+index);return `<article class="decision-card"><div class="decision-head"><span class="key-tag">${escapeHTML(c.key)}</span>${c.old.show==='0'?`<span class="hidden-tag">${escapeHTML(tr('hidden'))}</span>`:''}</div><p class="coords">(${escapeHTML(c.old.x)}, ${escapeHTML(c.old.y)}) → (${escapeHTML(c.new.x)}, ${escapeHTML(c.new.y)})</p><label for="${id}">${escapeHTML(tr('policyFor'))} · ${escapeHTML(c.key)}<select id="${id}" data-decision-key="${escapeHTML(c.key)}">${['','follow','keep','reset'].map(v=>`<option value="${v}"${v===selected?' selected':''}>${escapeHTML(tr(v||'choose'))}</option>`).join('')}</select></label><p class="choice-effect">${escapeHTML(!selected?tr('notChosen'):pos===undefined?tr('NUMBER_RANGE'):pos?tr('anchor')+': '+pos.join(', '):tr('auto'))}</p></article>`;}).join('');
 const countRows=Math.min(100,analysisState.changes.length);
 const tableRows=analysisState.changes.slice(0,100).map(c=>{const pos=labelPosition(c),policy=c.requiresDecision?choices[c.key]:c.old?'unchanged':'new';return `<tr><td><span class="key-tag">${escapeHTML(c.key)}</span></td><td>${escapeHTML(tr(c.status))}</td><td>${escapeHTML(c.new.text)}</td><td>${escapeHTML(c.new.x)} / ${escapeHTML(c.new.y)}</td><td>${escapeHTML(c.requiresDecision&&!choices[c.key]?tr('notChosen'):pos===undefined?tr('NUMBER_RANGE'):pos?pos.join(' / '):tr('auto'))}</td><td>${escapeHTML(tr(policy||'notChosen'))}</td><td>${escapeHTML(tr(c.old?.show==='0'?'hidden':'visible'))}</td></tr>`;}).join('');
 $('result').hidden=false;$('result').innerHTML=`<p class="eyebrow">${escapeHTML(tr('step2'))}</p><h2>${escapeHTML(tr('resultTitle'))}</h2><div class="stats">${Object.entries(counts).map(([k,n])=>`<div class="stat"><strong>${n}</strong><span>${escapeHTML(tr(k))}</span></div>`).join('')}</div><div class="result-grid"><section class="decision-panel"><h3>${escapeHTML(tr('policies'))}</h3><p class="policy-help">${escapeHTML(tr('policyHelp'))}</p>${required.length>25?`<div class="batch-actions"><span>${escapeHTML(tr('batch'))}:</span>${['follow','keep','reset'].map(v=>`<button data-batch="${v}">${escapeHTML(tr(v))}</button>`).join('')}</div>`:''}${cards||`<p>${escapeHTML(tr('noDecisions'))}</p>`}${pageCount>1?`<div class="pagination"><button id="previousDecision"${decisionPage===0?' disabled':''}>${escapeHTML(tr('previous'))}</button><span>${escapeHTML(tr('page',{page:decisionPage+1,total:pageCount}))}</span><button id="nextDecision"${decisionPage===pageCount-1?' disabled':''}>${escapeHTML(tr('next'))}</button></div>`:''}</section><section class="preview-panel"><h3>${escapeHTML(tr('preview'))}</h3>${previewSVG()}<div class="preview-legend"><span><i class="legend-dot old"></i>${escapeHTML(tr('oldPoint'))}</span><span><i class="legend-dot"></i>${escapeHTML(tr('newPoint'))}</span><span><i class="legend-dot label"></i>${escapeHTML(tr('approvedAnchor'))}</span></div><p class="preview-note">${escapeHTML(tr('previewNote'))}</p><p class="coords">${escapeHTML(analysisState.crs)} · X → / Y ↑</p></section></div><section class="ledger"><div class="ledger-heading"><h3>${escapeHTML(tr('ledger'))}</h3><span class="soft-note">${escapeHTML(tr('ledgerNote',{n:countRows,total:analysisState.changes.length}))}</span></div><div class="ledger-scroll" tabindex="0" role="region" aria-label="${escapeHTML(tr('ledger'))}"><table><thead><tr>${['key','state','text','point','label','policy','visibility'].map(k=>`<th scope="col">${escapeHTML(tr(k))}</th>`).join('')}</tr></thead><tbody>${tableRows}</tbody></table></div><p class="removed-note">${escapeHTML(tr('removedReceipt'))}: ${escapeHTML(analysisState.removed.length?analysisState.removed.join(', '):tr('noneRemoved'))}</p></section>`;
 for(const select of $('result').querySelectorAll('[data-decision-key]'))select.addEventListener('change',()=>{revision++;busy=false;if(select.value)choices[select.dataset.decisionKey]=select.value;else delete choices[select.dataset.decisionKey];renderResult();});
 for(const button of $('result').querySelectorAll('[data-batch]'))button.addEventListener('click',()=>{revision++;for(const c of required)if(!Object.hasOwn(choices,c.key))choices[c.key]=button.dataset.batch;renderResult();});
 if($('previousDecision'))$('previousDecision').onclick=()=>{decisionPage--;renderResult();};if($('nextDecision'))$('nextDecision').onclick=()=>{decisionPage++;renderResult();};
 setButtons();if(resultError)showError(resultError);else showStatus(pending.length?'pending':'ready',{n:pending.length||analysisState.changes.length},pending.length?'neutral':'ready');
 if(activeKey){const same=[...$('result').querySelectorAll('[data-decision-key]')].find(e=>e.dataset.decisionKey===activeKey);same?.focus({preventScroll:true});}
}
function runAnalysis(savedChoices){invalidate();try{analysisState=analyze(readInput());choices=Object.assign(Object.create(null),savedChoices||{});renderResult();}catch(error){invalidate();showError(error);}}
for(const side of ['old','new']){
 $(side+'CSV').addEventListener('input',()=>{fileVersions[side]++;projectVersion++;invalidate();renderMappings(side,true);});
 $(side+'CRS').addEventListener('input',()=>{projectVersion++;invalidate();});
 $(side+'File').addEventListener('change',async event=>{const file=event.target.files[0];invalidate('readFile');const own=++fileVersions[side],generation=clearGeneration;projectVersion++;if(!file)return;try{if(file.size>2000000)throw {code:'fileLarge'};const text=await file.text();if(own!==fileVersions[side]||generation!==clearGeneration)return;invalidate('loaded');$(side+'CSV').value=text;renderMappings(side,true);parseCSV(text);showStatus('loaded');}catch(error){if(own!==fileVersions[side]||generation!==clearGeneration)return;$(side+'CSV').value='';renderMappings(side);showError(error);}finally{event.target.value='';}});
}
$('lang').addEventListener('change',()=>{locale=$('lang').value;translate();});
$('analyze').addEventListener('click',()=>{projectVersion++;runAnalysis();});
$('demo').addEventListener('click',()=>{clearGeneration++;projectVersion++;invalidate('sample');for(const side of ['old','new']){$(side+'CSV').value=DEMO[side+'CSV'];$(side+'CRS').value=DEMO[side+'CRS'];mappings[side]={...(side==='old'?DEFAULT_OLD:DEFAULT_NEW)};renderMappings(side);}});
$('clear').addEventListener('click',()=>{clearGeneration++;projectVersion++;invalidate('empty');for(const side of ['old','new']){$(side+'CSV').value='';$(side+'CRS').value='';$(side+'File').value='';mappings[side]={...(side==='old'?DEFAULT_OLD:DEFAULT_NEW)};renderMappings(side);}$('projectFile').value='';});
$('projectFile').addEventListener('change',async event=>{const file=event.target.files[0];clearGeneration++;invalidate('readFile');const own=++projectVersion;if(!file)return;try{if(file.size>13000000)throw {code:'fileLarge'};const text=await file.text();if(own!==projectVersion)return;const project=parseProject(text);for(const side of ['old','new']){$(side+'CSV').value=project.input[side+'CSV'];$(side+'CRS').value=project.input[side+'CRS'];mappings[side]={...project.input[side+'Mapping']};renderMappings(side);}runAnalysis(project.decisions);showStatus('projectLoaded',{},'ready');}catch(error){if(own===projectVersion){invalidate();showError(error);}}finally{event.target.value='';}});
function download(contents,name,type){const url=URL.createObjectURL(new Blob([contents],{type})),link=document.createElement('a');link.href=url;link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('export').addEventListener('click',async()=>{if(!readyResult||busy)return;const token=revision,input=readInput(),decisions={...choices};busy=true;setButtons();showStatus('processing');try{const bytes=await exportZip(input,decisions);if(token!==revision)return;download(bytes,'label-rebase-bundle.zip','application/zip');showStatus('downloaded',{},'ready');}catch(error){if(token===revision)showError(error);}finally{if(token===revision){busy=false;setButtons();}}});
$('saveProject').addEventListener('click',()=>{if(!readyResult||busy)return;const input=readInput();rebase(input,choices);download(JSON.stringify({format:'label-rebase-project',version:1,input,decisions:{...choices}},null,2)+'\n','labelrebase-project.json','application/json');showStatus('saved',{},'ready');});
translate();
